# Generated by Django 3.1.7 on 2021-03-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='secondname',
            new_name='second_name',
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.SlugField(max_length=30),
        ),
    ]
